name: my_telemedicine
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_auth: ^5.11.0  # For authentication
  cloud_firestore: ^5.11.0  # For Firestore database
  firebase_storage: ^12.11.0  # For file storage
  
  google_sign_in: ^6.2.2
  sign_in_with_apple: latest_version

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true